language: node_js
node_js:
  - "6.1"

before_install:
   - npm install -g swagger
   - npm install -g mocha

   # Update docker-engine.
   - sudo apt-get update
   - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

   # Travis uses an older docker-composer (v1.4.2), we need to update it.
   - docker-compose --version
   - sudo rm /usr/local/bin/docker-compose
   - curl -L https://github.com/docker/compose/releases/download/1.8.0-rc2/docker-compose-`uname -s`-`uname -m` > docker-compose
   - chmod +x docker-compose
   - sudo mv docker-compose /usr/local/bin

   # Do AWS login for ECR.
   - pip install --user awscli
   - export PATH=$PATH:$HOME/.local/bin
   - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
   - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
   - $(aws ecr get-login --region us-west-2)

   # Compose docker containers.
   - docker-compose --version

services:
  - mongodb