version: '2'
services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:10010"
    networks:
      - mailord-net

  mailord-mongo:
    image: mongo
    networks:
      - mailord-net

networks:
  mailord-net:
    driver: bridge