swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw
  /health:
    x-swagger-router-controller: healthCtrl
    get:
      operationId: health
      description: Ensures the api is healthy
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/HealthResponse'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /account/{id}:
    x-swagger-router-controller: accountCtrl
    get:
      operationId: getAccountById
      description: returns the required account information
      parameters:
        - name: id
          in: path
          description: the account identifier
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/Account'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /template/{id}:
    x-swagger-router-controller: templateCtrl
    get:
      operationId: getTemplateById
      description: returns the required template by id
      parameters:
        - name: id
          in: path
          description: the template identifier
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/Template'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /masterLayout/{id}:
    x-swagger-router-controller: masterLayoutCtrl
    get:
      operationId: getMasterLayoutById
      description: returns the required master layout by id
      parameters:
        - name: id
          in: path
          description: the master layout identifier
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/MasterLayout'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /email/{id}:
    x-swagger-router-controller: emailMessageCtrl
    get:
      operationId: getEmailMessageById
      description: returns the required emailMessage by id
      parameters:
        - name: id
          in: path
          description: the emailMessage identifier
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/EmailMessage'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /email/send:
    x-swagger-router-controller: emailMessageCtrl
    post:
      operationId: sendEmail
      description: returns the required emailMessage by id
      parameters:
        - name: email
          in: body
          description: email message to send
          required: true
          schema:
            $ref: '#/definitions/EmailMessage'
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/EmailMessage'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
# complex objects have schema definitions
definitions:
  Template:
    properties:
      id:
        type: string
      accountId:
        type: string
      name:
        type: string
      subject:
        type: string
      body:
        type: string
      from:
        type: string
      active:
        type: boolean
      masterLayoutId:
        type: string
    required:
      - id
      - name
      - accountId
  MasterLayout:
    properties:
      id:
        type: string
      accountId:
        type: string
      name:
        type: string
      template: 
        type: string
    required:
      - id
      - accountId
      - name
      - template
  EmailMessage:
    properties:
      id:
        type: string
      template:
        type: string
      accountId: 
        type: string
      deliveryDate:
        type: string
      subject:
        type: string
      body:
        type: string
      from:
        type: string
      to:
        type: array
        items:
          type: string
      cc:
        type: string
        items:
          type: string
    required:
    - subject
    - body
    - to
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Account:
    type: object
    required:
      - id
      - accountName 
    properties:
      id:
        type: string
      accountName:
        type: string
  HealthResponse:
    type: object
    required:
      - status
    properties:
      status:
        type: string